int _putchar(char c);                     
char *_strcat(char *dest, char *src);
char *_strncat(char *dest, char *src, int n);                                                                              
char *_strncpy(char *dest, char *src, int n);
int _strcmp(char *s1, char *s2);
void reverse_array(int *a, int n);
unsigned int _strspn(char *s, char *accept);                                                                                       
char *_strpbrk(char *s, char *accept);                                                                                             
char *_strstr(char *haystack, char *needle);                                                                                       
void print_chessboard(char (*a)[8]);                                                                                               
void print_diagsums(int *a, int size);                                                                                             
void set_string(char **s, char *to);
